services:

  mysql:
    image: mysql:8.4
    container_name: shopkart-mysql
    environment:
      MYSQL_DATABASE: shopkart
      MYSQL_USER: shopkart_user
      MYSQL_PASSWORD: shopkartpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: tharunreddy04/shopkart-backend:${APP_VERSION}
    container_name: shopkart-backend
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: shopkart
      DB_USER: shopkart_user
      DB_PASSWORD: shopkartpassword
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    image: tharunreddy04/shopkart-frontend:${APP_VERSION}
    container_name: shopkart-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data: